name: azure-deploy-test

on:
  workflow_dispatch: # Manually triggered by the user in GitHub repo on the Actions tab

jobs:
  azure-deploy-test:
    name: deploy a resource group and storage account to azure
    uses: JasonCubic/azure-rg-and-st/.github/workflows/call.yaml@v0.1.1
    with:
      resource-group-name: rg-ga-test
      storage-account-prefix: storage
      deployment-mode: Complete
    secrets:
      tenant-id: c9b046ac-2035-4d3c-b81b-9722f126b124
      client-secret: ${{ secrets.CLIENT_SECRET }}
      client-id: ${{ secrets.CLIENT_ID }}
      subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
