name: azure-deploy-test

on:
  workflow_dispatch: # Manually triggered by the user in GitHub repo on the Actions tab

jobs:
  azure-deploy-test:
    name: deploy a resource group and storage account to azure
    uses: JasonCubic/reusable-workflow-pipeline/.github/workflows/rw-azure-deploy-rg-and-stg.yml@main
    with:
      tenant-id: c9b046ac-2035-4d3c-b81b-9722f126b124
      subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      resource-group-name: rg-ga-test
      client-id: ${{ secrets.CLIENT_ID }}
      # runs-on: '["self-hosted", "Linux", "X64"]'
    secrets:
      client-secret: ${{ secrets.CLIENT_SECRET }}
