name: hello-world-test

on:
  workflow_dispatch: # Manually triggered by the user in GitHub repo on the Actions tab

jobs:
  hello-world-test:
    name: call hello-world reusable workflow that is in another repo
    # https://github.blog/2022-02-10-using-reusable-workflows-github-actions/
    # uses: USER_OR_ORG_NAME/REPO_NAME/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@TAG_OR_BRANCH
    uses: JasonCubic/ga-hello-world/.github/workflows/call.yaml@v0.0.4
    with:
      who-to-greet: reusable workflow modules!
      runs-on: '["ubuntu-latest"]'
      # runs-on: '["self-hosted", "Linux", "X64"]'
