name: rw-test

on:
  workflow_dispatch:

jobs:
  rw-test:
    name: test calling rw in another repo
    # runs-on: [self-hosted, Linux, X64]
    # runs-on: ubuntu-latest
    # https://github.com/JasonCubic/reusable-workflow-pipeline

    # https://github.blog/2022-02-10-using-reusable-workflows-github-actions/
    # uses: USER_OR_ORG_NAME/REPO_NAME/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@TAG_OR_BRANCH
    uses: JasonCubic/reusable-workflow-pipeline/.github/workflows/reusable/hello-world/main.yml@main

    with:
      RUNS_ON: ubuntu-latest

    # name: test calling rw in another repo
    # # runs-on: [self-hosted, Linux, X64]
    # runs-on: ubuntu-latest
    # env:
    #   BOARD_NAME: TODO Task List
    #   OWNER: ${{ github.repository_owner }}
    #   REPO: ${{ github.event.repository.name }}
    #   ISSUE: ${{ github.event.issue.number }}

    # steps:
    #   # https://stackoverflow.com/questions/68407608/github-actions-do-not-run-a-job-if-issue-is-already-in-project
    #   - name: Check if issue is already in "${{ env.BOARD_NAME }}"
    #     run: |
    #       if curl -i -H 'Content-Type: application/json' -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query": "query($issue: Int!, $owner: String!, $repo: String!) { repository(owner: $owner, name: $repo) { issue(number: $issue) { projectCards { nodes { project { name } } } } } } ", "variables" : "{ \"issue\": '${ISSUE}', \"owner\": \"'${OWNER}'\", \"repo\": \"'${REPO}'\" }" }' https://git.t3.daimlertruck.com/api/graphql | grep "\b$BOARD_NAME\b"; then
    #         echo "Issue is already in Project '$BOARD_NAME', cancelling this workflow";
    #         echo "ALREADY_IN_BOARD=true" >> $GITHUB_ENV
    #       else
    #         echo "Issue is not in project '$BOARD_NAME', adding it to $BOARD_NAME."
    #         echo "ALREADY_IN_BOARD=false" >> $GITHUB_ENV
    #       fi
